/**
 * `help` and `completions` — both generated from the command table, so they
 * cannot drift from the commands they describe.
 */
import { PRODUCT_NAME } from "@lasercode/protocol";
import type { FlagSpecs } from "../args.js";
import type { Command } from "../command.js";
import { findCommand } from "../command.js";
import { CliError, ExitCode } from "../errors.js";
import { GLOBAL_FLAGS, flagsFor } from "../flags.js";
import { TOPICS, findTopic, renderCommandHelp, renderRootHelp } from "../help.js";

export const helpCommand: Command = {
  name: "help",
  group: "Shell",
  summary: "explain a command, or a topic",
  usage: `${PRODUCT_NAME} help [command|topic]`,
  description: `
With a command name, prints that command's help. With a topic name, prints a
page about something that spans commands.
`,
  positionals: [{ name: "command|topic", description: "What to explain", optional: true }],
  examples: [
    { note: `everything ${PRODUCT_NAME} can do`, command: `${PRODUCT_NAME} help` },
    { note: `how the \`${PRODUCT_NAME} pi\` passthrough works`, command: `${PRODUCT_NAME} help pi` },
    { note: "what doctor checks", command: `${PRODUCT_NAME} help doctor` },
  ],
  async run({ term, args, commands }) {
    const subject = args.positionals[0];
    if (!subject) {
      renderRootHelp(commands, term);
      return;
    }

    const command = findCommand(commands, subject);
    const topic = findTopic(subject);

    // A name that is both (pi, doctor) gets the topic, which is the longer read,
    // plus a pointer to the command's own flags.
    if (topic) {
      // Help is the answer to `piorbit help`, so it goes to stdout and can
      // be piped, the same as the generated command help.
      term.write(`${term.out.bold(topic.title)}\n`);
      for (const body of topic.body.trim().split("\n")) term.write(`${body}\n`);
      // A passthrough command's own `--help` belongs to the tool it wraps, so
      // pointing at it here would send the reader to the wrong help.
      if (command && !command.passthrough) {
        term.write("\n");
        term.write(`${term.out.dim(`Options: piorbit ${command.name} --help`)}\n`);
      }
      return;
    }
    if (command) {
      renderCommandHelp(command, term);
      return;
    }
    throw new CliError(`no command or topic called ${JSON.stringify(subject)}`, {
      exitCode: ExitCode.Usage,
      details: [
        `commands: ${commands.filter((c) => !c.hidden).map((c) => c.name).join(", ")}`,
        `topics:   ${TOPICS.map((t) => t.name).join(", ")}`,
      ],
      fix: `Run \`${PRODUCT_NAME} --help\`.`,
    });
  },
};

export const completionsCommand: Command = {
  name: "completions",
  group: "Shell",
  summary: "print a shell completion script",
  usage: `${PRODUCT_NAME} completions <bash|zsh|fish>`,
  description: `
Prints a completion script on stdout. It is generated from the same table that
generates --help, so a new command completes the day it exists.

Install it:

  bash   ${PRODUCT_NAME} completions bash > /etc/bash_completion.d/${PRODUCT_NAME}
         # or, without root:  ${PRODUCT_NAME} completions bash >> ~/.bashrc
  zsh    ${PRODUCT_NAME} completions zsh > "\${fpath[1]}/_${PRODUCT_NAME}"   # then: compinit
  fish   ${PRODUCT_NAME} completions fish > ~/.config/fish/completions/${PRODUCT_NAME}.fish
`,
  positionals: [{ name: "shell", description: "bash, zsh or fish" }],
  examples: [
    { note: "install for fish", command: `${PRODUCT_NAME} completions fish > ~/.config/fish/completions/${PRODUCT_NAME}.fish` },
    { note: "try it in this bash session", command: `source <(${PRODUCT_NAME} completions bash)` },
  ],
  async run({ term, args, commands }) {
    const shell = args.positionals[0];
    if (shell !== "bash" && shell !== "zsh" && shell !== "fish") {
      throw new CliError(shell ? `no completions for ${JSON.stringify(shell)}` : "completions needs a shell", {
        exitCode: ExitCode.Usage,
        fix: `Use one of: \`${PRODUCT_NAME} completions bash\`, \`zsh\`, \`fish\`.`,
      });
    }
    const visible = commands.filter((command) => !command.hidden);
    const script =
      shell === "bash" ? bashScript(visible) : shell === "zsh" ? zshScript(visible) : fishScript(visible);
    term.write(script.endsWith("\n") ? script : `${script}\n`);
  },
};

function longFlags(flags: FlagSpecs | undefined): string[] {
  return Object.entries(flagsFor(flags))
    .filter(([, spec]) => !spec.hidden)
    .flatMap(([name, spec]) => (spec.type === "boolean" ? [`--${name}`, `--no-${name}`] : [`--${name}`]));
}

function names(command: Command): string[] {
  return [command.name, ...(command.aliases ?? [])];
}

function bashScript(commands: readonly Command[]): string {
  const all = commands.flatMap(names).join(" ");
  const cases = commands
    .map((command) => `    ${names(command).join("|")})\n      opts="${longFlags(command.flags).join(" ")}" ;;`)
    .join("\n");
  return `# ${PRODUCT_NAME} bash completions. Generated by \`${PRODUCT_NAME} completions bash\`.
_${PRODUCT_NAME}() {
  local cur prev cmd i opts
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  cmd=""
  for (( i=1; i < COMP_CWORD; i++ )); do
    case "\${COMP_WORDS[i]}" in
      -*) ;;
      *) cmd="\${COMP_WORDS[i]}"; break ;;
    esac
  done

  # Everything after \`pi\` belongs to Pi; do not guess at its flags.
  if [[ "$cmd" == "pi" ]]; then
    COMPREPLY=()
    return 0
  fi

  case "$prev" in
    --agent-dir|--session-dir|--state-dir|--subagents-temp-root|--project|-P)
      COMPREPLY=( $(compgen -d -- "$cur") ); return 0 ;;
    --color)
      COMPREPLY=( $(compgen -W "auto always never" -- "$cur") ); return 0 ;;
  esac

  if [[ -z "$cmd" ]]; then
    COMPREPLY=( $(compgen -W "${all} ${longFlags(undefined).join(" ")} --version" -- "$cur") )
    return 0
  fi

  opts="${longFlags(undefined).join(" ")}"
  case "$cmd" in
${cases}
  esac
  COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}
complete -F _${PRODUCT_NAME} ${PRODUCT_NAME}
`;
}

function zshScript(commands: readonly Command[]): string {
  const list = commands.map((command) => `    '${command.name}:${escapeZsh(command.summary)}'`).join("\n");
  const cases = commands
    .map(
      (command) =>
        `      ${command.name})\n        _values 'option' ${longFlags(command.flags)
          .map((flag) => `'${flag}'`)
          .join(" ")} ;;`,
    )
    .join("\n");
  return `#compdef ${PRODUCT_NAME}
# ${PRODUCT_NAME} zsh completions. Generated by \`${PRODUCT_NAME} completions zsh\`.
_${PRODUCT_NAME}() {
  local -a commands
  commands=(
${list}
  )
  if (( CURRENT == 2 )); then
    _describe -t commands '${PRODUCT_NAME} command' commands
    return
  fi
  # Everything after \`pi\` belongs to Pi.
  [[ "\${words[2]}" == "pi" ]] && return
  case "\${words[2]}" in
${cases}
      *) _values 'option' ${longFlags(undefined)
        .map((flag) => `'${flag}'`)
        .join(" ")} ;;
  esac
}
_${PRODUCT_NAME} "$@"
`;
}

function fishScript(commands: readonly Command[]): string {
  const lines: string[] = [
    `# ${PRODUCT_NAME} fish completions. Generated by \`${PRODUCT_NAME} completions fish\`.`,
    `function __${PRODUCT_NAME}_no_command`,
    "  set -l tokens (commandline -opc)",
    "  test (count $tokens) -le 1",
    "end",
    `function __${PRODUCT_NAME}_is_pi`,
    "  set -l tokens (commandline -opc)",
    '  contains -- pi $tokens[2]',
    "end",
    "",
  ];
  for (const command of commands) {
    lines.push(
      `complete -c ${PRODUCT_NAME} -n '__${PRODUCT_NAME}_no_command' -a '${command.name}' -d '${escapeFish(command.summary)}'`,
    );
    for (const [name, spec] of Object.entries(flagsFor(command.flags))) {
      if (spec.hidden) continue;
      const short = spec.short ? ` -s ${spec.short}` : "";
      const takesValue = spec.type === "boolean" ? "" : " -r";
      lines.push(
        `complete -c ${PRODUCT_NAME} -n '__fish_seen_subcommand_from ${command.name}; and not __${PRODUCT_NAME}_is_pi'${short} -l ${name}${takesValue} -d '${escapeFish(spec.description)}'`,
      );
    }
  }
  for (const [name, spec] of Object.entries(GLOBAL_FLAGS)) {
    if (spec.hidden) continue;
    lines.push(
      `complete -c ${PRODUCT_NAME} -n '__${PRODUCT_NAME}_no_command' -l ${name}${spec.type === "boolean" ? "" : " -r"} -d '${escapeFish(spec.description)}'`,
    );
  }
  return lines.join("\n");
}

const escapeZsh = (text: string): string => text.replace(/'/g, "'\\''").replace(/:/g, "\\:");
const escapeFish = (text: string): string => text.replace(/'/g, "\\'");

export const metaCommands: readonly Command[] = [helpCommand, completionsCommand];
