// Generated by scripts/identity/generate.mjs from product.json. Do not edit.
// The channel names both the main process and the preload use.

export const IPC = {
  hostInfo: "laser:host/info",
  hostChanged: "laser:host/changed",
  hostRetry: "laser:host/retry",
  deepLink: "laser:deep-link",
  deepLinkPending: "laser:deep-link/pending",
  windowMinimize: "laser:window/minimize",
  windowToggleMaximize: "laser:window/toggle-maximize",
  windowClose: "laser:window/close",
  windowState: "laser:window/state",
  windowStateChanged: "laser:window/state-changed",
  themeSet: "laser:theme/set",
  directorySelect: "laser:directory/select",
  sourceFileOpen: "laser:source-file/open",
  microphoneStatus: "laser:microphone/status",
  microphoneRequest: "laser:microphone/request",
  microphoneSettings: "laser:microphone/settings",
  identity: "laser:identity",
  updateStatus: "laser:update/status",
  updateCheck: "laser:update/check",
  updateInstall: "laser:update/install",
  updateChanged: "laser:update/changed",
} as const;

export type IpcChannel = (typeof IPC)[keyof typeof IPC];
