/**
 * Public surface of the laser assistant-ui runtime layer.
 *
 * Components import from here; nothing below it talks to `HostClient` or the
 * reducer directly.
 */
export {
  AGENT_COMPLETION_DATA_PART,
  AGENT_COMPLETION_TOOL,
  AGENT_EVENT_DATA_PART,
  NOTICE_DATA_PART,
  TASK_EVENT_DATA_PART,
  agentCompletionOf,
  dialogActionReason,
  dialogToToolFields,
  projectMessages,
  projectSessionView,
  shareProjectedMessages,
  splitDialogs,
  toolStatus,
  toolDisplayResult,
  type AgentCompletionData,
  type AgentEventData,
  type TaskEventData,
  type ProjectedContentPart,
  type ProjectedMessageStatus,
  type ProjectedToolCallPart,
  type ProjectedToolStatus,
  type ProjectionInput,
  type ProjectionResult,
} from "./projection.js";

export {
  ARCHIVE_STORAGE_KEY,
  ATTENTION_ORDER,
  attentionRank,
  createArchiveStore,
  createThreadListAdapter,
  mergeSessions,
  sessionAttention,
  sessionTitle,
  sortSessions,
  threadListSignature,
  toThreadMetadata,
  type ArchiveStore,
  type RemoteThreadMetadata,
  type ThreadListDeps,
} from "./threadList.js";

export {
  FOLLOW_UP_QUEUE_PREFIX,
  PENDING_QUEUE_PREFIX,
  STEER_QUEUE_PREFIX,
  composerSendPlan,
  contentBlocksFromAppendMessage,
  createThreadAdapter,
  imageContentFromDataUrl,
  imageCountOfContentBlocks,
  isSteerQueueItemId,
  pendingIdOfQueueItemId,
  pendingQueueItem,
  pendingQueueItemId,
  queueItemId,
  queueItemsOf,
  requestIdOfInterruptPayload,
  resolveSendBehavior,
  sendToSession,
  textOfContentBlocks,
  uiResponseForApproval,
  uiResponseForInterrupt,
  type ComposerKeyState,
  type ComposerSendPlan,
  type InterruptAnswer,
  type RequestClient,
  type SendBehavior,
  type SendLane,
  type ThreadAdapterDeps,
} from "./adapter.js";

export { THEME_PREFS_NAMESPACE, useThemeSync } from "./prefs.js";
export { createSessionLauncher, isUnstartedSession, type NewSessionOptions, type SessionLauncher } from "./new-session.js";
export {
  activityDetailLevel,
  activityGroupDefaultOpen,
  setActivityDetailLevel,
  toolDetailsDefaultOpen,
  useActivityDetailLevel,
  type ActivityDetailLevel,
} from "./sessionPreferences.js";

export {
  forgetRememberedSessions,
  PROJECTS_STORAGE_KEY,
  PROJECT_STORAGE_KEY,
  LaserProvider,
  LaserThreadScope,
  useExtensionUi,
  useHostUiRequests,
  useLaser,
  useLaserStable,
  useLaserState,
  useLaserView,
  useSessionMeta,
  useThreadScopeRefusal,
  useToasts,
  useTrustPrompts,
  type ExtensionUi,
  type HostUiRequests,
  type TrustPrompts,
  type TrustRequest,
  type LaserActions,
  type MoveOptions,
  type LaserContextValue,
  type LaserStable,
  type LaserProviderProps,
  type LaserThreadScopeProps,
  type ScopedSessionShape,
  type SessionMeta,
  type ThreadScopeRefusal,
  type Toasts,
} from "./LaserProvider.js";
