/**
 * Public surface of the laser assistant-ui runtime layer.
 *
 * Components import from here; nothing below it talks to `HostClient` or the
 * reducer directly.
 */
export {
  AGENT_COMPLETION_DATA_PART,
  AGENT_COMPLETION_TOOL,
  AGENT_EVENT_DATA_PART,
  NOTICE_DATA_PART,
  TASK_EVENT_DATA_PART,
  agentCompletionOf,
  dialogActionReason,
  dialogToToolFields,
  projectMessages,
  projectSessionView,
  shareProjectedMessages,
  splitDialogs,
  toolStatus,
  toolDisplayResult,
  type AgentCompletionData,
  type AgentEventData,
  type TaskEventData,
  type ProjectedContentPart,
  type ProjectedMessageStatus,
  type ProjectedToolCallPart,
  type ProjectedToolStatus,
  type ProjectionInput,
  type ProjectionResult,
} from "./projection.js";

export {
  ATTENTION_ORDER,
  attentionRank,
  createArchiveStore,
  createThreadListAdapter,
  mergeSessions,
  sessionAttention,
  sessionTitle,
  sortSessions,
  threadListSignature,
  toThreadMetadata,
  type ArchiveStore,
  type RemoteThreadMetadata,
  type ThreadListDeps,
} from "./threadList.js";

export {
  FOLLOW_UP_QUEUE_PREFIX,
  PENDING_QUEUE_PREFIX,
  STEER_QUEUE_PREFIX,
  composerSendPlan,
  contentBlocksFromAppendMessage,
  createThreadAdapter,
  imageContentFromDataUrl,
  isSteerQueueItemId,
  pendingIdOfQueueItemId,
  pendingQueueItem,
  pendingQueueItemId,
  queueItemId,
  queueItemsOf,
  requestIdOfInterruptPayload,
  resolveSendBehavior,
  sendToSession,
  textOfContentBlocks,
  uiResponseForApproval,
  uiResponseForInterrupt,
  type ComposerKeyState,
  type ComposerSendPlan,
  type InterruptAnswer,
  type RequestClient,
  type SendBehavior,
  type SendLane,
  type ThreadAdapterDeps,
} from "./adapter.js";

export {
  DEVICE_KEYS,
  ENVIRONMENT_NAMESPACE,
  createDeviceStore,
  deviceStore,
  isLegacyDeviceKey,
  namespaceOf,
  type DeviceStorageStatus,
  type DeviceStore,
} from "./device-storage.js";
export { THEME_PREFS_NAMESPACE, useThemeSync } from "./prefs.js";
export { createSessionLauncher, isUnstartedSession, type NewSessionOptions, type SessionLauncher } from "./new-session.js";
export {
  SESSIONS_TAB_STORAGE_KEY,
  rememberSessionsTab,
  rememberedSessionsTab,
  sessionKindTab,
  type SessionKindTab,
} from "./session-tab-memory.js";
export {
  codeDestinationForSession,
  codeLandingKey,
  codeProjectForSession,
  creationTargetForDestination,
  destinationSessionForTab,
  emptyCodeDestination,
  initialMainDestination,
  isMainReady,
  isSessionInCodeProject,
  mainCodeProject,
  mainError,
  mainLandingKey,
  mainPath,
  mainTab,
  pendingSessionPath,
  projectReturnOf,
  provisionalSessionPath,
  rememberedCodeOf,
  rootCwdForSession,
  visibleSessionPath,
  type CodeDestination,
  type MainCreationTarget,
  type MainDestination,
  type MainTab,
  type MainTarget,
  type ProjectCodeDestination,
} from "./main-destination.js";
export {
  activityDetailLevel,
  activityGroupDefaultOpen,
  setActivityDetailLevel,
  toolDetailsDefaultOpen,
  useActivityDetailLevel,
  type ActivityDetailLevel,
} from "./sessionPreferences.js";

export {
  forgetRememberedSessions,
  LaserProvider,
  LaserThreadScope,
  useExtensionUi,
  useHostUiRequests,
  useCapability,
  useLaser,
  useLaserStable,
  useLaserState,
  useLaserView,
  useRendererPressure,
  useWholeTranscriptRefusal,
  useSessionMeta,
  useThreadScopeRefusal,
  useToasts,
  useTrustPrompts,
  type ExtensionUi,
  type HostUiRequests,
  type TrustPrompts,
  type TrustRequest,
  type LaserActions,
  type MoveOptions,
  type LaserContextValue,
  type LaserStable,
  type LaserProviderProps,
  type LaserThreadScopeProps,
  type ScopedSessionShape,
  type SessionMeta,
  type ThreadScopeRefusal,
  type Toasts,
  type WholeTranscriptRefusal,
} from "./LaserProvider.js";

export {
  capabilityError,
  capabilityFor,
  type CapabilityDecision,
  type CapabilityPresentation,
  type CapabilityRequirements,
  type CapabilityState,
  type EnvironmentCapability,
} from "./environment-capabilities.js";

export {
  DELIVERY_FALLBACK_MS,
  PENDING_TAIL_MAX_BYTES,
  PENDING_TAIL_MAX_ENTRIES,
  VIEW_CACHE_LIMITS,
  VIEW_HEAP_MODEL,
  createViewCache,
  pinReason,
  rendererViewsStore,
  type PinReason,
  type ReleaseOutcome,
  type RendererViewCounters,
  type ViewCache,
  type ViewCacheEnvironment,
  type ViewCacheLimits,
} from "./view-cache.js";

export {
  NO_TAIL_SINK,
  VIEW_TAIL_MAX_BYTES,
  VIEW_TAIL_MAX_ENTRIES,
  VIEW_TAIL_SCHEMA,
  VIEW_TAIL_SESSION_ID_MAX,
  captureViewTail,
  installViewTailSink,
  viewTailRetainedBytes,
  viewTailSink,
  type ViewTailDto,
  type ViewTailEntryDto,
  type ViewTailSink,
} from "./view-tail.js";

export { byteLength, measureView, type ViewMeasure } from "./view-measure.js";

export {
  PRESSURE_REFUSAL_MESSAGES,
  PressureRefusedError,
  RENDERER_PRESSURE_REFUSALS,
  RENDERER_PRESSURE_STEPS,
  RENDERER_PRESSURE_THRESHOLDS,
  createRendererPressureController,
  createRendererPressureSampler,
  registerEphemeralCache,
  releaseEphemeralCaches,
  type EphemeralCache,
  type EphemeralRelease,
  type RendererHostPressure,
  type RendererPressureController,
  type RendererPressureCounters,
  type RendererPressureRefusal,
  type RendererPressureRow,
  type RendererPressureSample,
  type RendererPressureState,
} from "./pressure/index.js";

export {
  TAIL_DATABASE_NAME,
  TAIL_HARD_LIMITS,
  TAIL_OMITTED_ATTACHMENT,
  TAIL_RECORD_SCHEMA,
  TAIL_SCAN_LIMITS,
  deviceCacheStore,
  tailCache,
  type DeviceCacheCounters,
  type TailBounds,
  type TailCacheState,
  type TailRecord,
  type TailRefusal,
} from "./tail-cache/index.js";
